# Generated by Django 3.1.6 on 2021-02-10 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogApi', '0002_auto_20210210_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likedBy',
            field=models.ManyToManyField(default=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likedBy',
            field=models.ManyToManyField(default=True, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
