# Generated by Django 3.1.6 on 2021-02-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0006_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='me', max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
