# Generated by Django 3.1.6 on 2021-02-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0007_auto_20210211_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
